# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job1:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        cp target/discovery-server-0.0.1-SNAPSHOT.jar /home/insight/tb
  job2:
    runs-on: self-hosted
    needs: job1
    steps:
    - name: Run App
      run: |
        pwd
        ls
        ./start.sh &
      shell: bash
      working-directory: /home/insight/tb

