# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run App  
      run: |
        echo $PATH
        pwd
        ls
        cp discovery-server-0.0.1-SNAPSHOT.jar /home/insight/tb
        java -jar discovery-server-0.0.1-SNAPSHOT.jar
      shell: bash
      working-directory: /home/insight/actions-runner/_work/SC-Discovery-Server/SC-Discovery-Server/target
      

