# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build & Deploy Service-Discovery

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy over SSH
      uses: kostya-ten/ssh-server-deploy@v4
      env:
        host: ${{ secrets.REMOTE_HOST }}
        user: ${{ secrets.REMOTE_USER }}
        private_key: ${{ secrets.SC_SECRET }}
        scp_source: "target/discovery-server-0.0.1-SNAPSHOT.jar"
        scp_target: "~/wb/SC-Discovery-Server/target"
        before_script: |
            df -h
        after_script: |
            whoami
            cd ~/wb/SC-Discovery-Server/script
            ./start.sh
        #EXCLUDE: "/dist/, /node_modules/"
        #INCLUDE: "*.jar"
